name: 'Zigbee Switch'
packageKey: 'zigbee-switch'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee switch devices"
vendorSupportInformation: "https://support.smartthings.com"

fingerprints:
  - manufacturer: "LEDVANCE"
    model: "PLUG COMPACT EU EM T"
    deviceProfileName: "switch-power-energy"
    id: "LEDVANCE/PLUG COMPACT EU EM T"
    deviceLabel: "SMART ZIGBEE COMPACT OUTDOOR PLUG EU"
  - manufacturer: "LEDVANCE"
    model: "PLUG EU EM T"
    deviceProfileName: "switch-power-energy"
    id: "LEDVANCE/PLUG COMPACT EU EM T"
    deviceLabel: "SMART ZIGBEE PLUG EU"