name: 'Matter Switch Scroll'
packageKey: 'matter-switch-scroll'
permissions:
  matter: {}
description: "SmartThings driver for Matter switch devices"
vendorSupportInformation: "https://support.smartthings.com"
